var a = null;
console.log("a =", a);
console.log("typeof a =", typeof a);
var b;
console.log("b =", b);
console.log("typeof b =", typeof b);
var c = undefined;
console.log("c =", c);
console.log("typeof c =", typeof c);
var d = "jitu";
console.log("d =", d);
console.log("typeof d =", typeof d);
console.log("null == undefined ->", null == undefined);
console.log("null === undefined ->", null === undefined);
var arr = [];
console.log("arr[0] =", arr[0]);
console.log("typeof arr[0] =", typeof arr[0]);
var obj = {};
console.log("obj.key =", obj.key);
console.log("typeof obj.key =", typeof obj.key);
